import Head from "next/head";
import Link from "next/link";
import { SignInButton } from "@clerk/nextjs";
import { SignOutButton } from "@clerk/nextjs";
import { useUser } from "@clerk/nextjs";
import {RouterOutputs} from "../utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime"

dayjs.extend(relativeTime);

      

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const {user} = useUser();

  console.log(user);

  if (!user) return null;

  return <div className="flex w-full gap-4 ">
    <img src= {user.imageUrl} 
    alt="Profile image" 
    className=" h-20 w-20 rounded-full"/>
    <input placeholder="Type something fun!" className="bg-transparent grow outline-none"></input>
  </div>

}
type PostWithUser = RouterOutputs["posts"]["getAll"][number]

const PostView = (props: PostWithUser) => {
  const {post, author } = props;
  return (
  <div key={post.id} className="p-4 gap-3 border-b border-slate-400 flex">
    <img src={author.profilePicture}  className=" h-14 w-14 rounded-full" />

    <div className="flex flex-col ">
      <div className="flex gap-2 font-bold text-slate-300"><span>{`@${author.username} `}</span>
      <span> {` ${dayjs(post.createdAt).fromNow()}`}</span>    
      </div>
    <span>{post.content}</span>
    
    </div>
  </div>)
}



export default function Home() {
  
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();


  if (isLoading) return <div> Loading... </div>
  
  if (!data) return <div> Something went wrong. oh no</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl ">
      <div className="flex border-b border-slate-400 p-4 ">
        {!user.isSignedIn && (
          <div className="flex justify-center">
            <SignInButton />
          </div>
        )}
        {!!user.isSignedIn && <CreatePostWizard />}
      </div>
      
      <div className="flex flex-col">
        {data?.map((fullPost)=> (
          <PostView {...fullPost} key={fullPost.post.id}/>
        ))}
      </div>
      </div>
      </main>
    </>
  );
}
 